const NFTFilteredarray = [
    {
      id: 1,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft5.svg",
    },
    {
      id: 2,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft6.svg",
    },
    {
      id: 3,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft7.svg",
    },
    {
      id: 4,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft8.svg",
    },
    {
      id: 5,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft1.svg",
    },
    {
      id: 6,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft2.svg",
    },
    {
      id: 7,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft3.svg",
    },
    {
      id: 8,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft4.svg",
    },
    {
      id: 9,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft9.svg",
    },
    {
      id: 10,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft10.svg",
    },
    {
      id: 11,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft11.svg",
    },
    {
      id: 12,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft12.svg",
    },
    {
      id: 13,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft13.svg",
    },
    {
      id: 14,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft14.svg",
    },
    {
      id: 15,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft15.svg",
    },
    {
      id: 16,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft16.svg",
    },
  ];

  export  default NFTFilteredarray;