 const NFTarray = [
    {
      id: 1,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft1.svg",
    },
    {
      id: 2,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft2.svg",
    },
    {
      id: 3,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft3.svg",
    },
    {
      id: 4,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft4.svg",
    },
    {
      id: 5,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft5.svg",
    },
    {
      id: 6,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft6.svg",
    },
    {
      id: 7,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft7.svg",
    },
    {
      id: 8,
      name: "Desert King",
      cost: 1,
      away: 2345,
      stay: "2 weeks",
      rating: 5,
      image: "../nft8.svg",
    },
  ];

  export  default NFTarray;